name: test
on:
  push:
    branches:
      - main
  pull_request:
env:
  CUCUMBER_PUBLISH_ENABLED:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: go build
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: go test -race -covermode atomic -coverprofile coverage.txt ./...
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: go run ./cmd/agoa --strict
  integration_test_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          bundler-cache: true
      - run: bundler exec cucumber --strict --tags 'not @go'
  integration_failure_test_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          bundler-cache: true
      - run: >
          bundler exec cucumber --strict --tags 'not @go' failures |
          tee /dev/stderr |
          grep '[0-9]\+ scenarios ([0-9]\+ failed)'
  action_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.
  dependent_test:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - go
          - ruby
        dependent:
          - directory: cloe
            build: rake build
            environment:
              - PATH=$PWD/bin:$PATH
          - directory: schemat
            build: cargo install --locked --path .
          - directory: stak
            build: |
              cargo install stak
              cargo build --profile release_test --package stak --package stak-compile --package stak-interpret
            environment:
              - PATH=$PWD/target/release_test:$PATH
              - STAK_ROOT=$PWD
          - directory: turtle-build
            build: cargo install --locked --path .
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
      - run: |
          for variable in ${{ join(matrix.dependent.environment, ' ') }}; do
            echo $variable >> ${{ github.env }}
          done
        working-directory: dependents/${{ matrix.dependent.directory }}
      - run: ${{ matrix.dependent.build }}
        working-directory: dependents/${{ matrix.dependent.directory }}
      - run: go install ./cmd/agoa
      - run: bundler
      - if: matrix.runner == 'go'
        run: agoa --strict
        working-directory: dependents/${{ matrix.dependent.directory }}
      - if: matrix.runner == 'ruby'
        run: |
          mkdir -p $feature_directory/support
          cp ${{ github.workspace }}/dependents/aruba.rb $feature_directory/support/aruba_go.rb

          bundler exec cucumber --strict --require $feature_directory $feature_directory
        working-directory: ${{ runner.temp }}
        env:
          BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
          feature_directory: ${{ github.workspace }}/dependents/${{ matrix.dependent.directory }}/features
  test:
    needs:
      - build
      - unit_test
      - integration_test
      - integration_test_test
      - integration_failure_test_test
      - dependent_test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
